version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - anime_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          #cpus: '0.001'
          memory: 512M
        reservations:
          #cpus: '0.0001'
          memory: 384M
    
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
    - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
    - "9090:9090"
    deploy:
      resources:
        limits:
          #cpus: '0.001'
          memory: 128M
        reservations:
          #cpus: '0.0001'
          memory: 96M
    
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    - "3000:3000"
    deploy:
      resources:
        limits:
          #cpus: '0.001'
          memory: 128M
        reservations:
          #cpus: '0.0001'
          memory: 64M
    
    
volumes:
  anime_data:
  
